# /// script
# requires-python = ">=3.10"
# dependencies = ["fonttools[woff]==4.66.0"]
# ///

import hashlib
import io
import urllib.request
import zipfile
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

RELEASE = "https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip"
RELEASE_SHA256 = "9883fdd4a49d4fb66bd8177ba6625ef9a64aa45899767dde3d36aa425756b11e"
WEIGHTS = {
    "REGULAR": (400, "extras/ttf/Inter-Regular.ttf"),
    "SEMI_BOLD": (600, "extras/ttf/Inter-SemiBold.ttf"),
}
UNICODES = [
    *range(0x20, 0x7F),
    *range(0xA0, 0x180),
    *range(0x2000, 0x2070),
    0x20AC,
    *range(0x2190, 0x2200),
]
# The OFL asks that the copyright and the license travel with the font.
NAME_IDS = [0, 1, 2, 3, 4, 5, 6, 13, 14]

ROOT = Path(__file__).resolve().parents[2]
WEB = ROOT / "web/packages/ui/src/fonts"
RUST = ROOT / "crates/op-diagram-render/src/measure/inter.rs"


def release() -> zipfile.ZipFile:
    with urllib.request.urlopen(RELEASE) as response:
        data = response.read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != RELEASE_SHA256:
        raise SystemExit(f"{RELEASE} has SHA-256 {digest}, expected {RELEASE_SHA256}")
    return zipfile.ZipFile(io.BytesIO(data))


# Without kerning, ligatures, or contextual alternates the browser draws each glyph at the advance
# the width table holds, so the daemon measures a label exactly as the browser lays it out. The
# font keeps the date of the release, so a second run writes the same bytes.
def subset_font(data: bytes) -> TTFont:
    font = TTFont(io.BytesIO(data), recalcTimestamp=False)
    options = subset.Options()
    options.layout_features = []
    options.hinting = False
    options.desubroutinize = True
    options.name_IDs = NAME_IDS
    options.notdef_outline = True
    options.flavor = "woff2"
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=UNICODES)
    subsetter.subset(font)
    return font


def segments(font: TTFont) -> list[tuple[int, list[int]]]:
    advances = font["hmtx"].metrics
    runs: list[tuple[int, list[int]]] = []
    for code, glyph in sorted(font.getBestCmap().items()):
        width = advances[glyph][0]
        if runs and runs[-1][0] + len(runs[-1][1]) == code:
            runs[-1][1].append(width)
        else:
            runs.append((code, [width]))
    return runs


def rust_table(name: str, runs: list[tuple[int, list[int]]]) -> str:
    rows = "".join(
        f"    (0x{first:04X}, &[{', '.join(map(str, widths))}]),\n" for first, widths in runs
    )
    return f"pub(super) const {name}: &[(u32, &[u16])] = &[\n{rows}];\n"


def main() -> None:
    archive = release()
    WEB.mkdir(parents=True, exist_ok=True)
    (WEB / "Inter-LICENSE.txt").write_bytes(archive.read("LICENSE.txt"))
    tables = []
    metrics = None
    for name, (weight, member) in WEIGHTS.items():
        font = subset_font(archive.read(member))
        target = WEB / f"inter-diagram-{weight}.woff2"
        font.save(target)
        print(f"{target.relative_to(ROOT)}: {target.stat().st_size} bytes")
        tables.append(rust_table(name, segments(font)))
        hhea = font["hhea"]
        metrics = (font["head"].unitsPerEm, hhea.ascent, hhea.descent)
    units_per_em, ascender, descender = metrics
    RUST.parent.mkdir(parents=True, exist_ok=True)
    RUST.write_text(
        "// Generated by `mise run font` from Inter 4.1: edit assets/fonts/inter.py, not this file.\n\n"
        f"pub(super) const UNITS_PER_EM: f32 = {units_per_em}.0;\n"
        f"pub(super) const ASCENDER: f32 = {ascender}.0;\n"
        f"pub(super) const DESCENDER: f32 = {descender}.0;\n\n"
        + "\n".join(tables)
    )
    print(f"{RUST.relative_to(ROOT)}: units per em {units_per_em}, ascender {ascender}, descender {descender}")


if __name__ == "__main__":
    main()
