flowchart LR
  rectangle[Rectangle]
  rounded(Rounded)
  stadium([Stadium])
  subroutine[[Subroutine]]
  cylinder[(Cylinder)]
  circle((Circle))
  double(((Double circle)))
  asymmetric>Asymmetric]
  diamond{Diamond}
  hexagon{{Hexagon}}
  lean_right[/Lean right/]
  lean_left[\Lean left\]
  trapezoid[/Trapezoid\]
  inverted[\Inverted trapezoid/]
  bare
  quoted["a ] b; c --> d"]
  lines[one<br>two<BR/>three<br />four]
  codes["#quot;quoted#quot; #35;1 #lt;tag#gt; #unknown; #"]
