import { FLOW_ROUTE } from "@open-planner/task-ui"

import type { Binding } from "./types"

export const bindings: ReadonlyArray<Binding> = [
  {
    id: "rows.down",
    keys: "j",
    scope: "rows",
    label: "Move down",
    group: "Navigation",
    run: (ctx) => ctx.cursor.moveBy(1),
  },
  {
    id: "rows.up",
    keys: "k",
    scope: "rows",
    label: "Move up",
    group: "Navigation",
    run: (ctx) => ctx.cursor.moveBy(-1),
  },
  {
    id: "rows.open",
    keys: "Enter",
    scope: "rows",
    label: "Open task",
    group: "Navigation",
    run: (ctx) => {
      const row = ctx.cursor.focusedRow()
      if (row !== undefined) ctx.navigate(row)
    },
  },
  {
    id: "detail.back",
    keys: "Escape",
    scope: "detail",
    label: "Back",
    group: "Navigation",
    run: (ctx) => ctx.detail.escape(),
  },
  {
    id: "flow.back",
    keys: "Escape",
    scope: "flow",
    label: "Leave the flow",
    group: "Navigation",
    run: (ctx) => ctx.back(),
  },
  {
    id: "go.list",
    keys: ["g", "l"],
    scope: "global",
    label: "Go to list",
    group: "Navigation",
    run: (ctx) => ctx.navigate("/"),
  },
  {
    id: "go.flow",
    keys: ["g", "f"],
    scope: "global",
    label: "Go to the flow",
    group: "Navigation",
    run: (ctx) => ctx.navigate(FLOW_ROUTE),
  },
  {
    id: "go.parent",
    keys: ["g", "p"],
    scope: "detail",
    label: "Go to parent",
    group: "Navigation",
    run: (ctx) => ctx.detail.goToParent(),
  },
  {
    id: "detail.flow",
    keys: "f",
    scope: "detail",
    label: "Show the flow of this task",
    group: "Task",
    run: (ctx) => ctx.detail.showFlow(),
  },
  {
    id: "detail.parent",
    keys: "p",
    scope: "detail",
    label: "Set / change parent",
    group: "Task",
    run: (ctx) => ctx.detail.editParent(),
  },
  {
    id: "detail.subtask",
    keys: "s",
    scope: "detail",
    label: "Add subtask",
    group: "Task",
    run: (ctx) => ctx.detail.addSubtask(),
  },
  {
    id: "detail.tags",
    keys: "t",
    scope: "detail",
    label: "Add a tag",
    group: "Task",
    run: (ctx) => ctx.detail.editTags(),
  },
  {
    id: "task.copy-id",
    keys: "mod+.",
    scope: "global",
    label: "Copy task id",
    group: "Task",
    run: (ctx) => ctx.copy.taskId(),
  },
  {
    id: "palette.home",
    keys: "mod+k",
    scope: "global",
    label: "Open the command palette",
    group: "Search",
    run: (ctx) => ctx.palette.open("home"),
  },
  {
    id: "palette.search",
    keys: "/",
    scope: "global",
    label: "Search tasks",
    group: "Search",
    run: (ctx) => ctx.palette.open("search"),
  },
  // The palette's input holds the focus and answers ↑ ↓ ↵ Esc itself, which is the only way those
  // keys can coexist with typing. This one catches Esc when the focus has left the input.
  {
    id: "palette.close",
    keys: "Escape",
    scope: "palette",
    label: "Close the palette",
    group: "Search",
    run: (ctx) => ctx.overlay("palette").close(),
  },
  {
    id: "help.toggle",
    keys: "?",
    scope: "global",
    label: "Toggle this help",
    group: "Help",
    run: (ctx) => ctx.overlay("help").toggle(),
  },
  {
    id: "help.close.escape",
    keys: "Escape",
    scope: "help",
    label: "Close help",
    group: "Help",
    run: (ctx) => ctx.overlay("help").close(),
  },
  {
    id: "help.close.question",
    keys: "?",
    scope: "help",
    label: "Close help",
    group: "Help",
    run: (ctx) => ctx.overlay("help").close(),
  },
]
